### ISSUE TITLE
Jetty in Maven fails

### ISSUE THREAD

**Issue by mdorf** [Bibliome/alvisnlp#100]
I'm getting this error when trying to run AlvisNLP in Jetty, per your instructions.

```
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
Oct 09, 2019 2:34:45 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  fr.inra.maiage.bibliome.alvisnlp.web
[ERROR] failed AlvisNLP/ML REST API
java.lang.IncompatibleClassChangeError: class com.sun.jersey.spi.scanning.AnnotationScannerListener$AnnotatedClassVisitor can not implement org.objectweb.asm.ClassVisitor, because it is not an interface (org.objectweb.asm.ClassVisitor is in unnamed module of loader org.mortbay.jetty.webapp.WebA
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
```
I've tried running it in both Java 8 and Java 11, using several different variations of 9.x Jetty Maven plugin

**Comment by rbossy** [comment]
`alvisnlp-rest` support has been dropped. Issue is thus moot.
