### ISSUE TITLE
[metadata] Tees n'a pas de documentation

### ISSUE THREAD

**Issue by jibe-b** [Bibliome/alvisnlp#37]
Tees n'a pas de documentation, ou tout du moins, l'invocation de alvisnlp -moduleDoc Tees retourne l'erreur

> Exception in thread "main" org.bibliome.util.clio.CLIOException: java.lang.reflect.InvocationTargetException
    at org.bibliome.util.clio.CLIOParser.processOption(CLIOParser.java:154)
    at org.bibliome.util.clio.CLIOParser.parse(CLIOParser.java:116)
    at alvisnlp.app.cli.AbstractAlvisNLP.run(AbstractAlvisNLP.java:1045)
    at alvisnlp.app.cli.AlvisNLP.main(AlvisNLP.java:85)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.bibliome.util.clio.CLIOParser.processOption(CLIOParser.java:145)
    ... 3 more
Caused by: org.bibliome.util.service.UnsupportedServiceException: alias: Tees
    at org.bibliome.util.service.CompositeServiceFactory.getServiceByAlias(CompositeServiceFactory.java:129)
    at alvisnlp.app.cli.AbstractAlvisNLP.getModuleDocumentation(AbstractAlvisNLP.java:384)
    at alvisnlp.app.cli.AbstractAlvisNLP.moduleDoc(AbstractAlvisNLP.java:447)
    ... 8 more

**Comment by rbossy** [comment]
alvisnlp -moduleDoc TEESTrain
    alvisnlp -moduleDoc TEESClassify
